### ISSUE TITLE
Epic: Yearn for the Sea

### ISSUE THREAD

**Issue by anaisbetts** [arquivolta/docs#1]
### What do we need in order to start finding people to help out

- [ ] A Manifesto aka Project Description (aka this repo)
- [x] A Discord Server
- [ ] Some tasks to spin out so people don't spin their wheels
- [ ] ~~(probably) documentation on how to install Arch in WSL2, so that they can e.g. start to package up some of the suggestions in https://github.com/arquivolta/wsl-extras/issues/1~~
