### ISSUE TITLE
Theming notes

### ISSUE THREAD

**Issue by anaisbetts** [arquivolta/docs#11]
## For GTK+

1. Install `win11-gtk-theme-git`
2. In `/etc/fonts/conf.d` set `<fontconfig><dir>/mnt/c/Windows/Fonts</dir></fontconfig>` and run `fc-cache`
3. `dconf load /` this:

```
[org/gnome/desktop/interface]
document-font-name='Segoe UI 13'
font-antialiasing='grayscale'
font-hinting='slight'
font-name='Segoe UI 13'
gtk-theme='windows11-GTKtheme'
monospace-font-name='Consolas 13'

[org/gnome/desktop/wm/preferences]
titlebar-font='Segoe UI Bold 13'
```

## TODO:

- [ ] Pull `win11-gtk-theme-git` into Repo
- [ ] Create a new package `wsl-theme-integration` that sets up fonts and saves the file we need to dconf load into a known location
- [ ] Run the `dconf load` command......somehow. We can't run it during install because systemd is borked, and it needs to run in user context
