### ISSUE TITLE
Epic: System Optimization and Updates

### ISSUE THREAD

**Issue by anaisbetts** [arquivolta/docs#6]
## Concept

Arquivolta should ship with a lot of the system optimization suggestions set up, so that users don't have to dig through the Arch Wiki. In particular, Arquivolta should:

- [ ] Enable paccache.timer
- [ ] Nag users to update if they haven't done so in awhile
- [ ] Disable or defer anything we don't need to run in WSL

### Notes / Helpful Links

- http://0pointer.de/blog/projects/three-levels-of-off - masking services in systemd
- https://www.freedesktop.org/software/systemd/man/systemd-analyze.html
- http://0pointer.de/blog/projects/blame-game.html
- https://systemd-by-example.com/
